version: 0.2

phases:
  install:
    commands:
      -echo "No dependencies needed for a static HTML webiste."

build:
  commands:
    - echo "Building the project..."

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .